name: money_manager
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - matplotlib
  - pip
  - pip:
    - anyio==4.11.0
    - APScheduler==3.9.1
    - cachetools==5.5.2
    - certifi==2025.10.5
    - charset-normalizer==3.4.4
    - contourpy==1.3.3
    - customtkinter==5.2.2
    - cycler==0.12.1
    - darkdetect==0.8.0
    - fonttools==4.60.1
    - google-api-core==2.10.2
    - google-api-python-client==2.54.0
    - google-auth==2.10.0
    - google-auth-httplib2==0.2.0
    - google-auth-oauthlib==0.4.6
    - googleapis-common-protos==1.71.0
    - h11==0.14.0
    - httpcore==0.16.3
    - httplib2==0.31.0
    - httpx==0.23.3
    - idna==3.11
    - kiwisolver==1.4.9
    - numpy==2.3.4
    - oauthlib==3.3.1
    - packaging==25.0
    - pillow==12.0.0
    - protobuf==4.25.8
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - python-telegram-bot==20.0
    - pytz==2025.2
    - requests==2.32.5
    - requests-oauthlib==2.0.0
    - rfc3986==1.5.0
    - rsa==4.9.1
    - six==1.17.0
    - sniffio==1.3.1
    - typing_extensions==4.15.0
    - tzdata==2025.2
    - tzlocal==5.3.1
    - uritemplate==4.2.0
    - urllib3==2.5.0
